/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan3;

/**
 *
 * @author Wildan
 */
public class PenilaianMK1 extends javax.swing.JFrame {

    /**
     * Creates new form PenilaianMK1
     */
    public PenilaianMK1() {
        initComponents();
        this.setTitle("Formulir Penilaian");
        this.setLocationRelativeTo(this);
        nilaiAngka.setEnabled(false);
        nilaiHuruf.setEnabled(false);
        validate.setEnabled(false);
        tentukanNama();
    }
    
   public void tentukanNama(){
        String listNama[] = {"Nuna Firda", "Maulana Ishak", "Citra Mirna", "Sugiharto","Utrodus Said"};
        for (int i = 0; i < listNama.length; i++) {
            if(selectNim.getSelectedIndex() == i){
                tampilNama.setText(listNama[i]);
            }
       }
   }
   
   public void kalkulasiNilai(){
        validate.setEnabled(false);
        int nilaiKehadiran = Integer.parseInt(kehadiran.getText()) *10/100;
        int nilaiTugas = Integer.parseInt(tugasMandiri.getText())*20/100;
        int nilaiUts = Integer.parseInt(uts.getText())*25/100;
        int nilaiUas = Integer.parseInt(uas.getText())*45/100;
        
        int totalNilai = nilaiKehadiran + nilaiTugas + nilaiUts + nilaiUas;
        nilaiAngka.setText(String.valueOf(totalNilai));
        nilaiAngka.setEnabled(true);
        
        if(totalNilai >= 91 && totalNilai <=100){
            nilaiHuruf.setText("A");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 86 && totalNilai <=90){
            nilaiHuruf.setText("A-");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 81 && totalNilai <=85){
            nilaiHuruf.setText("B+");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 76 && totalNilai <=80){
            nilaiHuruf.setText("B");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 71 && totalNilai <=75){
            nilaiHuruf.setText("B-");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 66 && totalNilai <=70){
            nilaiHuruf.setText("C+");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 61 && totalNilai <=65){
            nilaiHuruf.setText("C");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 56 && totalNilai <=60){
            nilaiHuruf.setText("C-");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 51 && totalNilai <= 55){
            nilaiHuruf.setText("D");
            nilaiHuruf.setEnabled(true);
        }else if(totalNilai >= 0 && totalNilai <=50){
            nilaiHuruf.setText("E");
            nilaiHuruf.setEnabled(true);
        }
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        selectNim = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tampilNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kehadiran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tugasMandiri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        uts = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        uas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nilaiAngka = new javax.swing.JTextField();
        nilaiHuruf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        validate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULIR PENILAIAN MATA KULIAH");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulir"));

        jLabel3.setText("NIM");

        selectNim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1855201002", "1855201003", "1855201004", "1855201005", "1855201006" }));
        selectNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNimActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        tampilNama.setText("tampilNama");

        jLabel5.setText("Kehadiran 10%");

        kehadiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kehadiranActionPerformed(evt);
            }
        });

        jLabel6.setText("Tugas Mandiri 20%");

        jLabel7.setText("UTS 25%");

        jLabel8.setText("UAS 45%");

        jLabel9.setText("Nilai Angka");

        jLabel10.setText("Nilai Huruf");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        validate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        validate.setForeground(new java.awt.Color(255, 0, 0));
        validate.setText("Mohon Periksa Form Yang Tersedia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(validate))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nilaiAngka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(tugasMandiri, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kehadiran, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uas)
                            .addComponent(uts)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tampilNama)
                            .addComponent(selectNim, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tampilNama))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(uts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tugasMandiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(uas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nilaiAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(validate))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALGORITMA DAN PEMROGRAMAN 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(199, 199, 199))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(184, 184, 184))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kehadiranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kehadiranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
       try{
          kalkulasiNilai();
       } catch(Exception e){
           System.out.println(e);
           validate.setEnabled(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNimActionPerformed
                // TODO add your handling code here:
                tentukanNama();
    }//GEN-LAST:event_selectNimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenilaianMK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenilaianMK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenilaianMK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenilaianMK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenilaianMK1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kehadiran;
    private javax.swing.JTextField nilaiAngka;
    private javax.swing.JTextField nilaiHuruf;
    private javax.swing.JComboBox<String> selectNim;
    private javax.swing.JLabel tampilNama;
    private javax.swing.JTextField tugasMandiri;
    private javax.swing.JTextField uas;
    private javax.swing.JTextField uts;
    private javax.swing.JLabel validate;
    // End of variables declaration//GEN-END:variables
}
